#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using WarScript.Bytecode;
using WarScript.Context;
using WarScript.Context.Definition;
using WarScript.Expression;
using WarScript.Expression.Value;
using WarScript.Statement;

namespace WarScript
{
    public class WarScriptLanguage
    {
        // ── Cached expression singletons for the parser ──
        public readonly ConstantExpression NullExpr;
        public readonly ConstantExpression TrueExpr;
        public readonly ConstantExpression FalseExpr;
        public readonly ThisExpression ThisExpr;

        // ── Consolidated halt flags for fast abort checking ──
        [Flags]
        public enum HaltFlag
        {
            None      = 0,
            Exception = 1,
            Return    = 2,
            Break     = 4,
            Next      = 8,
            Yield     = 16,
        }
        public HaltFlag HaltFlags;

        public readonly DefinitionContext DefinitionContext;
        public readonly MemoryContext MemoryContext;
        public readonly ExceptionContext ExceptionContext;
        public readonly ReturnContext ReturnContext;
        public readonly NextContext NextContext;
        public readonly BreakContext BreakContext;
        public readonly ClassInstanceContext ClassInstanceContext;
        public readonly IExpression DefaultStep;

        public readonly Func<string, string?>? FileResolver;
        public readonly Action<WarScriptLanguage, string>? Logger;

        internal readonly Dictionary<string, DefinitionScope> ImportCache = new();
        internal readonly HashSet<string> ImportStack = new();

        /// <summary>
        /// Names declared with <c>const</c> or generated by <c>enum</c>.
        /// The compiler rejects assignment to these names.
        /// </summary>
        internal readonly HashSet<string> ConstantNames = new();

        private readonly DefinitionScope _definitionScope;
        private readonly MemoryScope _memoryScope;

        public readonly string ScriptName;

        private List<Token.Token> _tokens;

        private CompositeStatement? _cachedStatement;
        private CompiledFunction? _cachedCompiled;
        private WarVM? _cachedVM;

        public readonly DefinitionScope GlobalDefinitionScope;
        public readonly MemoryScope GlobalMemoryScope;

        public MemoryScope UserMemoryScope => _memoryScope;

        /// <summary>
        /// Maximum number of bytecode instructions a single Run() or Call()
        /// invocation may execute before the VM raises an exception and stops.
        /// 
        /// Set to 0 (default) to disable budgeting (unlimited execution).
        /// Recommended values: 100,000 for tick functions, 1,000,000 for Run().
        ///
        /// When the budget is exhausted, the VM raises "Instruction budget exceeded"
        /// which can be caught by begin/rescue like any other exception. If uncaught,
        /// the script stops cleanly and the game continues.
        /// </summary>
        public int InstructionBudget { get; set; }

        // ── Source-map debugger ──

        /// <summary>
        /// Set this to receive callbacks when the VM hits a breakpoint or step
        /// point. Set to null to disable debugging (zero overhead).
        ///
        /// <code>
        ///   script.DebugHook = ctx => {
        ///       Console.WriteLine($"Paused at {ctx.FunctionName}:{ctx.Line}");
        ///       foreach (var local in ctx.Locals)
        ///           Console.WriteLine($"  {local.Key} = {local.Value}");
        ///       ctx.Action = StepMode.StepOver;
        ///   };
        /// </code>
        /// </summary>
        public DebugHook? DebugHook { get; set; }

        private readonly HashSet<int> _breakpoints = new();

        /// <summary>Add a breakpoint at a source line number.</summary>
        public void AddBreakpoint(int line) => _breakpoints.Add(line);

        /// <summary>Remove a breakpoint at a source line number.</summary>
        public bool RemoveBreakpoint(int line) => _breakpoints.Remove(line);

        /// <summary>Remove all breakpoints.</summary>
        public void ClearBreakpoints() => _breakpoints.Clear();

        /// <summary>Get all active breakpoint line numbers.</summary>
        public IReadOnlyCollection<int> Breakpoints => _breakpoints;

        /// <summary>
        /// Internal: the VM reads this to check breakpoints.
        /// Returns true if the given line has a breakpoint set.
        /// </summary>
        internal bool HasBreakpoint(int line) => _breakpoints.Contains(line);

        /// <summary>
        /// Maximum bytes of heap allocation a single Run() or Call() invocation
        /// may perform before the VM raises an exception and stops.
        ///
        /// Set to 0 (default) to disable memory budgeting (unlimited).
        /// Recommended values: 1_000_000 (1MB) for tick functions,
        /// 10_000_000 (10MB) for Run().
        ///
        /// Tracks allocations of strings, arrays, and class instances.
        /// Numeric and boolean values are stack-allocated and not counted.
        /// When the budget is exhausted, the VM raises "Memory budget exceeded"
        /// which can be caught by begin/rescue.
        /// </summary>
        public long MemoryBudget { get; set; }

        /// <summary>
        /// String interner for reducing GC pressure. Short strings created by
        /// the VM (concatenation results, ToString() conversions) are deduplicated
        /// through this cache. Pre-allocated integer strings (0–999) are returned
        /// without any hashing. Shared across all VMs and coroutines.
        /// </summary>
        internal readonly StringInterner Strings = new();

        // ── Coroutine support ──
        // Uses BytecodeCoroutine (VM suspend/resume) when the function has
        // bytecode, falls back to tree-walk Coroutine otherwise.
        private readonly List<ICoroutine> _coroutines = new();
        private int _nextCoroutineId = 1;

        public bool IsYielded { get; private set; }
        public YieldType YieldedType { get; private set; }
        public double YieldedWaitDuration { get; private set; }

        public WarScriptLanguage(
            string scriptName,
            string sourceCode,
            Func<string, string?>? fileResolver,
            Action<WarScriptLanguage, string>? logger)
        {
            ScriptName = scriptName;
            FileResolver = fileResolver;
            Logger = logger;

            NullExpr = new ConstantExpression(WarValue.Null);
            TrueExpr = new ConstantExpression(WarValue.True);
            FalseExpr = new ConstantExpression(WarValue.False);
            ThisExpr = new ThisExpression(this);

            DefinitionContext = new DefinitionContext(this);
            MemoryContext = new MemoryContext(this);
            ExceptionContext = new ExceptionContext(this);
            ReturnContext = new ReturnContext();
            NextContext = new NextContext();
            BreakContext = new BreakContext();
            ClassInstanceContext = new ClassInstanceContext();
            DefaultStep = new ConstantExpression(WarValue.FromNumeric(1.0));

            _tokens = LexicalParser.Parse(sourceCode);

            var nativeDefinitionScope = DefinitionContext.NewScope();
            var nativeMemoryScope = MemoryContext.NewScope();
            nativeMemoryScope.Poolable = false;

            DefinitionContext.PushScope(nativeDefinitionScope);
            MemoryContext.PushScope(nativeMemoryScope);

            GlobalDefinitionScope = nativeDefinitionScope;
            GlobalMemoryScope = nativeMemoryScope;

            _definitionScope = DefinitionContext.NewScope();
            _memoryScope = MemoryContext.NewScope();
            _memoryScope.Poolable = false;

            DefinitionContext.EndScope();
            MemoryContext.EndScope();
        }

        // ────────────────────────────────────────────────────────
        //  Parse + compile (lazy, cached)
        // ────────────────────────────────────────────────────────

        /// <summary>
        /// Ensure the script has been parsed and compiled to bytecode.
        /// Called automatically by Run() and Call(). Safe to call multiple
        /// times — parsing and compilation are cached.
        /// Must be called with _definitionScope pushed on DefinitionContext.
        /// </summary>
        private void EnsureCompiled()
        {
            if (_cachedStatement == null && _cachedCompiled == null)
            {
                var statement = new CompositeStatement(this, null, ScriptName);
                StatementParser.Parse(this, _tokens, statement);
                _cachedCompiled = Compiler.CompileScript(this, statement, _definitionScope);

                // Discard the AST — bytecode is the source of truth.
                // This frees all Statement/Expression nodes for GC while
                // keeping the DefinitionScope tree (function names, class
                // details, compiled bytecode) intact.
                DiscardAST(_definitionScope);
            }
            else if (_cachedCompiled == null && _cachedStatement != null)
            {
                _cachedCompiled = Compiler.CompileScript(this, _cachedStatement, _definitionScope);
                _cachedStatement = null;
                DiscardAST(_definitionScope);
            }
        }

        /// <summary>
        /// Recursively null out all AST Statement references in a DefinitionScope tree.
        /// After compilation, only the bytecode is needed — the AST can be GC'd.
        /// </summary>
        private static void DiscardAST(DefinitionScope scope)
        {
            foreach (var f in scope.Functions)
            {
                if (f is NativeFunctionDefinition) continue;
                f.Statement = null;
            }
            foreach (var c in scope.ClassDefinitions)
            {
                c.Statement = null;
                DiscardAST(c.GetDefinitionScope());
            }
        }

        /// <summary>
        /// Returns the cached VM instance, creating it once on first use.
        /// The VM resets its own internal state on each Run/RunFunction call,
        /// so the same instance is safe to reuse across all invocations.
        /// </summary>
        private WarVM EnsureVM()
        {
            return _cachedVM ??= new WarVM(this);
        }

        // ────────────────────────────────────────────────────────
        //  Hot reload — swap source code, preserve runtime state
        // ────────────────────────────────────────────────────────

        /// <summary>
        /// Replace the script source code with new code, re-parse, and re-compile
        /// all functions and classes — without re-executing top-level statements
        /// and without clearing global variable state.
        ///
        /// After Reload():
        /// - All function definitions are updated to the new source.
        ///   The next Call() will execute the new bytecode.
        /// - Global variables (hp, entities, arrays, etc.) are preserved.
        /// - Existing class instances keep their old definition. New instances
        ///   created after reload use the new class definition.
        /// - All active coroutines are stopped (they reference old bytecode).
        /// - Function handles obtained via GetFunction() before reload are stale.
        ///   Call GetFunction() again to get the new handle.
        ///
        /// Typical usage during development:
        /// <code>
        ///   // File watcher detects a change
        ///   var newSource = File.ReadAllText("patrol.ws");
        ///   script.Reload(newSource);
        ///   tickFunc = script.GetFunction("tick", 1);  // re-acquire handle
        /// </code>
        /// </summary>
        public void Reload(string newSourceCode)
        {
            // 1. Stop all coroutines — they hold VMs with old bytecode
            _coroutines.Clear();

            // 2. Clear old definitions (functions, classes)
            //    The MemoryScope (_memoryScope) is deliberately NOT cleared —
            //    global variables and class instance state survive the reload.
            _definitionScope.Clear();

            // 3. Clear all caches
            _cachedStatement = null;
            _cachedCompiled = null;
            _cachedVM = null;
            ImportCache.Clear();
            ConstantNames.Clear();

            // 4. Clear any lingering exception/halt state
            if (ExceptionContext.IsRaised())
                ExceptionContext.RescueException();
            HaltFlags = HaltFlag.None;

            // 5. Re-lex from new source
            _tokens = LexicalParser.Parse(newSourceCode);

            // 6. Re-parse and re-compile (but do NOT execute top-level code)
            DefinitionContext.PushScope(_definitionScope);
            MemoryContext.PushScope(_memoryScope);

            try
            {
                EnsureCompiled();
            }
            finally
            {
                DefinitionContext.EndScope();
                MemoryContext.EndScope();
            }
        }

        // ────────────────────────────────────────────────────────
        //  Bytecode serialization — skip parse+compile at load time
        // ────────────────────────────────────────────────────────

        /// <summary>
        /// Save the compiled bytecode to a binary stream. The script must
        /// have been compiled first (via Run() or EnsureCompiled).
        ///
        /// Typical build-time usage:
        /// <code>
        ///   var script = new WarScriptLanguage("patrol", source, null, null);
        ///   script.Run();
        ///   using var fs = File.Create("patrol.wsbc");
        ///   script.SaveBytecode(fs);
        /// </code>
        /// </summary>
        public void SaveBytecode(Stream stream)
        {
            // Ensure we have something to save
            DefinitionContext.PushScope(_definitionScope);
            MemoryContext.PushScope(_memoryScope);
            try { EnsureCompiled(); }
            finally
            {
                DefinitionContext.EndScope();
                MemoryContext.EndScope();
            }

            using var w = new System.IO.BinaryWriter(stream, System.Text.Encoding.UTF8, leaveOpen: true);
            BytecodeSerializer.Save(w, _cachedCompiled!, _definitionScope);
        }

        /// <summary>
        /// Load pre-compiled bytecode from a binary stream, replacing any
        /// existing definitions. This skips the lexer, parser, and compiler
        /// entirely — the script is ready to Call() immediately.
        ///
        /// Global variable state (_memoryScope) is preserved, just like Reload().
        /// Native functions (registered via WarScriptLibraryRegistry) are unaffected.
        ///
        /// Typical runtime usage:
        /// <code>
        ///   using var fs = File.OpenRead("patrol.wsbc");
        ///   script.LoadBytecode(fs);
        ///   var tick = script.GetFunction("tick", 1);
        ///   script.Call(tick, dt);
        /// </code>
        /// </summary>
        public void LoadBytecode(Stream stream)
        {
            // Stop coroutines referencing old bytecode
            _coroutines.Clear();

            // Clear old definitions and caches
            _definitionScope.Clear();
            _cachedStatement = null;
            _cachedCompiled = null;
            _cachedVM = null;
            ImportCache.Clear();
            ConstantNames.Clear();

            if (ExceptionContext.IsRaised())
                ExceptionContext.RescueException();
            HaltFlags = HaltFlag.None;

            // Load from binary
            using var r = new System.IO.BinaryReader(stream, System.Text.Encoding.UTF8, leaveOpen: true);
            var (topLevel, scope) = BytecodeSerializer.Load(r, this, GlobalDefinitionScope);

            // Merge loaded definitions into _definitionScope
            scope.CopyLocalDefinitionsTo(_definitionScope);
            _cachedCompiled = topLevel;
        }

        // ────────────────────────────────────────────────────────
        //  Run — execute the full script via bytecode VM
        // ────────────────────────────────────────────────────────

        /// <summary>
        /// Parse, compile, and execute the script. On first call this
        /// parses the source and compiles all functions to bytecode.
        /// Subsequent calls reuse the cached bytecode.
        /// </summary>
        public void Run()
        {
            DefinitionContext.PushScope(_definitionScope);
            MemoryContext.PushScope(_memoryScope);

            try
            {
                EnsureCompiled();
                var vm = EnsureVM();
                vm.Run(_cachedCompiled!);
            }
            finally
            {
                DefinitionContext.EndScope();
                MemoryContext.EndScope();

                if (ExceptionContext.IsRaised())
                    ExceptionContext.PrintStackTrace();

                HaltFlags = HaltFlag.None;
            }
        }

        // ────────────────────────────────────────────────────────
        //  Call — host invokes a WarScript function (tick, events)
        // ────────────────────────────────────────────────────────

        /// <summary>
        /// Call a WarScript function from the host (C#/Unity).
        /// Uses bytecode when available (always after Run() has been called).
        /// This is the hot path for game integration — tick loops, event handlers.
        /// </summary>
        public void Call(FunctionDefinition function, params WarValue[] arguments)
        {
            if (function.Compiled != null)
            {
                CallBytecode(function, arguments);
                return;
            }

            // Fallback: tree-walk for functions not yet compiled
            // (e.g. Call() before Run(), or native function wrappers)
            CallTreeWalk(function, arguments);
        }

        private void CallBytecode(FunctionDefinition function, WarValue[] arguments)
        {
            DefinitionContext.PushScope(_definitionScope);
            MemoryContext.PushScope(_memoryScope);
            // Push a scope for function-local variables accessed via SetGlobal.
            // Parented to _memoryScope, matching the VM's OP_CALL behavior.
            MemoryContext.PushScope(MemoryContext.NewScope(UserMemoryScope));

            try
            {
                var vm = EnsureVM();
                vm.RunFunction(function.Compiled!, arguments);
            }
            finally
            {
                MemoryContext.EndScope();  // function-local scope
                DefinitionContext.EndScope();
                MemoryContext.EndScope();
                ReturnContext.Reset();
                HaltFlags &= ~HaltFlag.Return;

                if (ExceptionContext.IsRaised())
                    ExceptionContext.PrintStackTrace();

                HaltFlags = HaltFlag.None;
            }
        }

        private void CallTreeWalk(FunctionDefinition function, WarValue[] arguments)
        {
            DefinitionContext.PushScope(_definitionScope);
            MemoryContext.PushScope(_memoryScope);
            MemoryContext.PushScope(MemoryContext.NewScope());

            try
            {
                var details = function.Details;
                for (var i = 0; i < details.Arguments.Count; i++)
                {
                    MemoryContext.GetScope().SetLocal(
                        details.Arguments[i],
                        i < arguments.Length ? arguments[i] : WarValue.Null);
                }

                function.Statement!.Execute();
            }
            finally
            {
                MemoryContext.EndScope();
                DefinitionContext.EndScope();
                MemoryContext.EndScope();
                ReturnContext.Reset();
                HaltFlags &= ~HaltFlag.Return;

                if (ExceptionContext.IsRaised())
                    ExceptionContext.PrintStackTrace();

                HaltFlags = HaltFlag.None;
            }
        }

        // ────────────────────────────────────────────────────────
        //  Function lookup
        // ────────────────────────────────────────────────────────

        public FunctionDefinition? GetFunction(string functionName, int arguments)
        {
            return _definitionScope.GetFunction(functionName, arguments);
        }

        public bool HasFunction(string functionName, int argumentsSize)
        {
            return _definitionScope.ContainsFunction(functionName, argumentsSize);
        }

        /// <summary>
        /// Convenience method: raises an exception and returns a null WarValue.
        /// Used by operators to combine error raising and return in one line.
        /// </summary>
        public WarValue RaiseException(string message)
        {
            return ExceptionContext.RaiseException(message);
        }

        // ────────────────────────────────────────────────────────
        //  Yield support
        // ────────────────────────────────────────────────────────

        public void SetYielded(YieldType type, double waitDuration)
        {
            IsYielded = true;
            HaltFlags |= HaltFlag.Yield;
            YieldedType = type;
            YieldedWaitDuration = waitDuration;
        }

        public void ClearYield()
        {
            IsYielded = false;
            HaltFlags &= ~HaltFlag.Yield;
            YieldedType = YieldType.NextTick;
            YieldedWaitDuration = 0;
        }

        // ────────────────────────────────────────────────────────
        //  Coroutine support (tree-walk — see note at field decl)
        // ────────────────────────────────────────────────────────

        public int StartCoroutine(string functionName, WarValue[] args, bool loop = false)
        {
            var argCount = args?.Length ?? 0;
            var function = _definitionScope.GetFunction(functionName, argCount);
            if (function == null)
            {
                ExceptionContext.RaiseException(
                    $"Coroutine function '{functionName}' with {argCount} arguments is not defined");
                return -1;
            }

            var id = _nextCoroutineId++;
            var safeArgs = args ?? Array.Empty<WarValue>();

            if (function.Compiled != null)
            {
                var bco = new BytecodeCoroutine(
                    this, function.Compiled, _definitionScope, _memoryScope,
                    safeArgs, loop, id);
                _coroutines.Add(bco);
                bco.Resume();
            }
            else
            {
                var coroutine = new Coroutine(
                    this, function, _definitionScope, _memoryScope,
                    safeArgs, loop, id);
                _coroutines.Add(coroutine);
                coroutine.Resume();
            }

            return id;
        }

        public bool StopCoroutine(int id)
        {
            for (var i = _coroutines.Count - 1; i >= 0; i--)
            {
                if (_coroutines[i].Id == id)
                {
                    _coroutines.RemoveAt(i);
                    return true;
                }
            }
            return false;
        }

        public void StopAllCoroutines() => _coroutines.Clear();

        public int TickCoroutines(double dt)
        {
            for (var i = _coroutines.Count - 1; i >= 0; i--)
            {
                var co = _coroutines[i];
                if (!co.IsReady(dt)) continue;
                co.Resume();
                if (co.IsComplete) _coroutines.RemoveAt(i);
            }
            return _coroutines.Count;
        }

        public int ActiveCoroutineCount => _coroutines.Count;
    }
}
