#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;
using WarScript.Attributes;

namespace WarScript.Editor
{
    /// <summary>
    /// Editor tool that scans all assemblies for [WsModule] classes and generates
    /// the Register() + LibraryInfo code as .g.cs files next to the source.
    ///
    /// Menu: WarScript → Generate Bindings
    ///
    /// Generated files are real .cs files checked into source control.
    /// Unity compiles them normally. Rider sees them normally. No DLL needed.
    /// </summary>
    public static class WsBindingGenerator
    {
        private const string Header = "// <auto-generated by WsBindingGenerator — do not edit manually>\n";

        [MenuItem("WarScript/Generate Bindings")]
        public static void GenerateAll()
        {
            var count = 0;
            var assemblies = AppDomain.CurrentDomain.GetAssemblies();

            foreach (var assembly in assemblies)
            {
                Type[] types;
                try { types = assembly.GetTypes(); }
                catch { continue; }

                foreach (var type in types)
                {
                    var moduleAttr = type.GetCustomAttribute<WsModuleAttribute>();
                    if (moduleAttr == null) continue;

                    if (!type.IsClass)
                    {
                        Debug.LogWarning($"[WsBindingGenerator] {type.FullName} has [WsModule] but is not a class. Skipping.");
                        continue;
                    }

                    var source = GenerateForType(type, moduleAttr);
                    if (source == null) continue;

                    var sourcePath = FindSourceFile(type.Name);
                    if (sourcePath == null)
                    {
                        Debug.LogWarning($"[WsBindingGenerator] Cannot find source file for {type.Name}. Skipping.");
                        continue;
                    }

                    var outputPath = Path.Combine(
                        Path.GetDirectoryName(sourcePath)!,
                        type.Name + ".g.cs");

                    // Skip if unchanged
                    if (File.Exists(outputPath) && File.ReadAllText(outputPath) == source)
                        continue;

                    File.WriteAllText(outputPath, source);
                    count++;
                    Debug.Log($"[WsBindingGenerator] Generated: {outputPath}");
                }
            }

            if (count > 0)
            {
                AssetDatabase.Refresh();
                Debug.Log($"[WsBindingGenerator] Done — {count} file(s) generated.");
            }
            else
            {
                Debug.Log("[WsBindingGenerator] All bindings up to date.");
            }
        }

        // ────────────────────────────────────────────────────────
        //  Source file lookup
        // ────────────────────────────────────────────────────────

        private static string? FindSourceFile(string className)
        {
            // Search for ClassName.cs in Assets and Packages
            var guids = AssetDatabase.FindAssets($"{className} t:TextAsset");
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                if (path.EndsWith($"/{className}.cs") || path.EndsWith($"\\{className}.cs"))
                    return path;
            }

            // Fallback: brute-force search
            var files = Directory.GetFiles(Application.dataPath, $"{className}.cs", SearchOption.AllDirectories);
            if (files.Length > 0)
                return "Assets" + files[0].Substring(Application.dataPath.Length).Replace('\\', '/');

            // Also search Packages
            var packagesPath = Path.Combine(Application.dataPath, "..", "Packages");
            if (Directory.Exists(packagesPath))
            {
                files = Directory.GetFiles(packagesPath, $"{className}.cs", SearchOption.AllDirectories);
                if (files.Length > 0)
                    return files[0].Replace('\\', '/');
            }

            return null;
        }

        // ────────────────────────────────────────────────────────
        //  Code generation
        // ────────────────────────────────────────────────────────

        private static string? GenerateForType(Type type, WsModuleAttribute moduleAttr)
        {
            var functions = new List<FuncInfo>();

            foreach (var method in type.GetMethods(
                         BindingFlags.Public | BindingFlags.Instance |
                         BindingFlags.Static | BindingFlags.DeclaredOnly))
            {
                var funcAttr = method.GetCustomAttribute<WsFunctionAttribute>();
                if (funcAttr == null) continue;

                var wsName = !string.IsNullOrEmpty(funcAttr.Name)
                    ? funcAttr.Name
                    : ToSnakeCase(method.Name);

                functions.Add(new FuncInfo
                {
                    Method = method,
                    WsName = wsName!,
                    Doc = funcAttr.Doc ?? "",
                    Returns = !string.IsNullOrEmpty(funcAttr.Returns)
                        ? funcAttr.Returns
                        : InferReturnsDoc(method.ReturnType)
                });
            }

            if (functions.Count == 0)
            {
                Debug.LogWarning($"[WsBindingGenerator] {type.Name} has [WsModule] but no [WsFunction] methods. Skipping.");
                return null;
            }

            // Find [WsScript] field/property
            string? scriptField = FindScriptField(type);

            var isStatic = type.IsAbstract && type.IsSealed;
            var sb = new StringBuilder();

            sb.AppendLine(Header);
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using WarScript;");
            sb.AppendLine("using WarScript.Context.Definition;");
            sb.AppendLine("using WarScript.Expression.Value;");
            sb.AppendLine();

            var ns = type.Namespace;
            var indent = "";
            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
                indent = "    ";
            }

            var staticKw = isStatic ? "static " : "";
            sb.AppendLine($"{indent}public {staticKw}partial class {type.Name}");
            sb.AppendLine($"{indent}{{");

            // ── Register method ──
            var registerStatic = isStatic ? "static " : "";
            sb.AppendLine($"{indent}    public {registerStatic}void Register(WarScriptLanguage __script, DefinitionScope __scope)");
            sb.AppendLine($"{indent}    {{");

            if (scriptField != null)
                sb.AppendLine($"{indent}        {scriptField} = __script;");

            foreach (var f in functions)
            {
                var parameters = f.Method.GetParameters();
                var wsParamNames = parameters
                    .Where(p => p.GetCustomAttribute<WsRawArgsAttribute>() == null)
                    .Select(p => $"\"{p.Name}\"");

                sb.AppendLine();
                sb.AppendLine($"{indent}        __scope.AddFunction(new NativeFunctionDefinition(");
                sb.AppendLine($"{indent}            new FunctionDetails(\"{f.WsName}\", new List<string> {{ {string.Join(", ", wsParamNames)} }}),");
                sb.AppendLine($"{indent}            (__args) =>");
                sb.AppendLine($"{indent}            {{");

                // Marshal arguments
                int argIdx = 0;
                foreach (var p in parameters)
                {
                    if (p.GetCustomAttribute<WsRawArgsAttribute>() != null)
                    {
                        sb.AppendLine($"{indent}                var @{SafeName(p.Name)} = __args;");
                    }
                    else
                    {
                        sb.AppendLine($"{indent}                {TypeName(p.ParameterType)} @{SafeName(p.Name)} = {ArgMarshal(p.ParameterType, argIdx)};");
                        argIdx++;
                    }
                }

                // Call and marshal return
                var callArgs = string.Join(", ", parameters.Select(p => $"@{SafeName(p.Name)}"));
                var prefix = f.Method.IsStatic ? $"{type.Name}." : "this.";

                if (f.Method.ReturnType == typeof(void))
                {
                    sb.AppendLine($"{indent}                {prefix}{f.Method.Name}({callArgs});");
                    sb.AppendLine($"{indent}                return WarValue.Null;");
                }
                else
                {
                    sb.AppendLine($"{indent}                var __result = {prefix}{f.Method.Name}({callArgs});");
                    sb.AppendLine($"{indent}                return {ReturnMarshal(f.Method.ReturnType)};");
                }

                sb.AppendLine($"{indent}            }},");
                sb.AppendLine($"{indent}            \"{Esc(f.Doc)}\",");
                sb.AppendLine($"{indent}            \"{Esc(f.Returns)}\"));");
            }

            sb.AppendLine($"{indent}    }}");

            // ── LibraryInfo property ──
            sb.AppendLine();
            sb.AppendLine($"{indent}    public {registerStatic}WarScriptLibraryRegistry.LibraryInfo LibraryInfo => new WarScriptLibraryRegistry.LibraryInfo");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        Name = \"{Esc(moduleAttr.Name)}\",");
            sb.AppendLine($"{indent}        Description = \"{Esc(moduleAttr.Description ?? "")}\",");
            sb.AppendLine($"{indent}        Register = {(isStatic ? "" : "this.")}Register");
            sb.AppendLine($"{indent}    }};");

            sb.AppendLine($"{indent}}}");
            if (!string.IsNullOrEmpty(ns)) sb.AppendLine("}");

            return sb.ToString();
        }

        // ────────────────────────────────────────────────────────
        //  Helpers
        // ────────────────────────────────────────────────────────

        private static string? FindScriptField(Type type)
        {
            foreach (var f in type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance))
                if (f.GetCustomAttribute<WsScriptAttribute>() != null) return f.Name;
            foreach (var p in type.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance))
                if (p.GetCustomAttribute<WsScriptAttribute>() != null) return p.Name;
            return null;
        }

        private static string ArgMarshal(Type t, int i)
        {
            if (t == typeof(double)) return $"NativeHelper.NumericArg(__args, {i})";
            if (t == typeof(int)) return $"(int)NativeHelper.NumericArg(__args, {i})";
            if (t == typeof(float)) return $"(float)NativeHelper.NumericArg(__args, {i})";
            if (t == typeof(string)) return $"NativeHelper.TextArg(__args, {i})";
            if (t == typeof(bool)) return $"(__args[{i}].IsLogical ? __args[{i}].LogicalValue : __args[{i}].IsNumeric && __args[{i}].Numeric != 0)";
            if (t.FullName == "WarScript.Expression.Value.WarValue") return $"__args[{i}]";
            if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(List<>))
                return $"NativeHelper.ArrayArg(__args, {i}).ArrayValue";
            return $"NativeHelper.NativeArg<{TypeName(t)}>(__args, {i})";
        }

        private static string ReturnMarshal(Type t)
        {
            if (t == typeof(double) || t == typeof(int) || t == typeof(float))
                return "WarValue.FromNumeric(__result)";
            if (t == typeof(string))
                return "__result != null ? WarValue.FromText(__result) : WarValue.Null";
            if (t == typeof(bool))
                return "WarValue.FromLogical(__result)";
            if (t.FullName == "WarScript.Expression.Value.WarValue")
                return "__result";
            return "WarValue.FromNativeObject(__result)";
        }

        private static string TypeName(Type t)
        {
            if (t == typeof(double)) return "double";
            if (t == typeof(int)) return "int";
            if (t == typeof(float)) return "float";
            if (t == typeof(string)) return "string";
            if (t == typeof(bool)) return "bool";
            if (t == typeof(void)) return "void";
            if (t.FullName == "WarScript.Expression.Value.WarValue") return "WarValue";
            if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(List<>))
                return $"List<{TypeName(t.GetGenericArguments()[0])}>";
            return t.Name;
        }

        private static string InferReturnsDoc(Type t)
        {
            if (t == typeof(double) || t == typeof(int) || t == typeof(float)) return "NumericValue";
            if (t == typeof(string)) return "TextValue";
            if (t == typeof(bool)) return "LogicalValue";
            if (t == typeof(void)) return "null";
            return "WarValue";
        }

        private static string ToSnakeCase(string name)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < name.Length; i++)
            {
                if (char.IsUpper(name[i]))
                {
                    if (i > 0) sb.Append('_');
                    sb.Append(char.ToLowerInvariant(name[i]));
                }
                else sb.Append(name[i]);
            }
            return sb.ToString();
        }

        private static string SafeName(string name) =>
            name == "base" || name == "class" || name == "event" || name == "object" || name == "string"
                ? name
                : name;

        private static string Esc(string s) =>
            s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n");

        private struct FuncInfo
        {
            public MethodInfo Method;
            public string WsName;
            public string Doc;
            public string Returns;
        }
    }
}
#endif
