#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;
using WarScript.Attributes;

namespace WarScript.Editor
{
    /// <summary>
    /// Editor tool that scans all assemblies for [WsModule] classes and generates
    /// the Register() + LibraryInfo code as .g.cs files next to the source.
    ///
    /// Menu: WarScript → Generate Bindings
    ///
    /// Generated files are real .cs files checked into source control.
    /// Unity compiles them normally. Rider sees them normally. No DLL needed.
    /// </summary>
    public static class WsBindingGenerator
    {
        private const string Header = "// <auto-generated by WsBindingGenerator — do not edit manually>\n";

        [MenuItem("WarScript/Generate Bindings")]
        public static void GenerateAll()
        {
            var count = 0;
            var assemblies = AppDomain.CurrentDomain.GetAssemblies();

            foreach (var assembly in assemblies)
            {
                Type[] types;
                try { types = assembly.GetTypes(); }
                catch { continue; }

                foreach (var type in types)
                {
                    var moduleAttr = type.GetCustomAttribute<WsModuleAttribute>();
                    if (moduleAttr == null) continue;

                    if (!type.IsClass)
                    {
                        Debug.LogWarning($"[WsBindingGenerator] {type.FullName} has [WsModule] but is not a class. Skipping.");
                        continue;
                    }

                    var source = GenerateForType(type, moduleAttr);
                    if (source == null) continue;

                    var sourcePath = FindSourceFile(type.Name);
                    if (sourcePath == null)
                    {
                        Debug.LogWarning($"[WsBindingGenerator] Cannot find source file for {type.Name}. Skipping.");
                        continue;
                    }

                    var outputPath = Path.Combine(
                        Path.GetDirectoryName(sourcePath)!,
                        type.Name + ".g.cs");

                    // Skip if unchanged
                    if (File.Exists(outputPath) && File.ReadAllText(outputPath) == source)
                        continue;

                    File.WriteAllText(outputPath, source);
                    count++;
                    Debug.Log($"[WsBindingGenerator] Generated: {outputPath}");
                }
            }

            if (count > 0)
            {
                AssetDatabase.Refresh();
                Debug.Log($"[WsBindingGenerator] Done — {count} file(s) generated.");
            }
            else
            {
                Debug.Log("[WsBindingGenerator] All bindings up to date.");
            }
        }

        // ────────────────────────────────────────────────────────
        //  Source file lookup
        // ────────────────────────────────────────────────────────

        private static string? FindSourceFile(string className)
        {
            // Search for ClassName.cs in Assets and Packages
            var guids = AssetDatabase.FindAssets($"{className} t:TextAsset");
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                if (path.EndsWith($"/{className}.cs") || path.EndsWith($"\\{className}.cs"))
                    return path;
            }

            // Fallback: brute-force search
            var files = Directory.GetFiles(Application.dataPath, $"{className}.cs", SearchOption.AllDirectories);
            if (files.Length > 0)
                return "Assets" + files[0].Substring(Application.dataPath.Length).Replace('\\', '/');

            // Also search Packages
            var packagesPath = Path.Combine(Application.dataPath, "..", "Packages");
            if (Directory.Exists(packagesPath))
            {
                files = Directory.GetFiles(packagesPath, $"{className}.cs", SearchOption.AllDirectories);
                if (files.Length > 0)
                    return files[0].Replace('\\', '/');
            }

            return null;
        }

        // ────────────────────────────────────────────────────────
        //  Code generation
        // ────────────────────────────────────────────────────────

        private static string? GenerateForType(Type type, WsModuleAttribute moduleAttr)
        {
            var functions = new List<FuncInfo>();

            foreach (var method in type.GetMethods(
                         BindingFlags.Public | BindingFlags.Instance |
                         BindingFlags.Static | BindingFlags.DeclaredOnly))
            {
                var funcAttr = method.GetCustomAttribute<WsFunctionAttribute>();
                if (funcAttr == null) continue;

                var wsName = !string.IsNullOrEmpty(funcAttr.Name)
                    ? funcAttr.Name
                    : ToSnakeCase(method.Name);

                functions.Add(new FuncInfo
                {
                    Method = method,
                    WsName = wsName!,
                    Doc = funcAttr.Doc ?? "",
                    Returns = !string.IsNullOrEmpty(funcAttr.Returns)
                        ? funcAttr.Returns
                        : InferReturnsDoc(method.ReturnType)
                });
            }

            // Collect [WsConst] fields
            var constants = new List<ConstInfo>();
            foreach (var field in type.GetFields(
                         BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly))
            {
                var constAttr = field.GetCustomAttribute<WsConstAttribute>();
                if (constAttr == null) continue;
                if (!field.IsLiteral) continue; // must be const

                constants.Add(new ConstInfo
                {
                    Field = field,
                    WsName = constAttr.Name ?? field.Name
                });
            }

            // Collect [WsEnum] nested enums
            var enums = new List<EnumInfo>();
            foreach (var nested in type.GetNestedTypes(BindingFlags.Public | BindingFlags.DeclaredOnly))
            {
                if (!nested.IsEnum) continue;
                var enumAttr = nested.GetCustomAttribute<WsEnumAttribute>();
                if (enumAttr == null) continue;

                var wsName = enumAttr.Name ?? nested.Name;
                var members = new List<(string Name, int Value)>();
                foreach (var name in Enum.GetNames(nested))
                    members.Add((name, (int)Enum.Parse(nested, name)));

                enums.Add(new EnumInfo { WsName = wsName, Members = members });
            }

            if (functions.Count == 0 && constants.Count == 0 && enums.Count == 0)
            {
                Debug.LogWarning($"[WsBindingGenerator] {type.Name} has [WsModule] but no [WsFunction], [WsConst], or [WsEnum] members. Skipping.");
                return null;
            }

            // Find [WsScript] field/property
            string? scriptField = FindScriptField(type);

            var isStatic = type.IsAbstract && type.IsSealed;
            var sb = new StringBuilder();

            sb.AppendLine(Header);
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using WarScript;");
            sb.AppendLine("using WarScript.Context.Definition;");
            sb.AppendLine("using WarScript.Expression.Value;");
            sb.AppendLine();

            var ns = type.Namespace;
            var indent = "";
            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
                indent = "    ";
            }

            var staticKw = isStatic ? "static " : "";
            sb.AppendLine($"{indent}public {staticKw}partial class {type.Name}");
            sb.AppendLine($"{indent}{{");

            // ── Register method ──
            var registerStatic = isStatic ? "static " : "";
            sb.AppendLine($"{indent}    public {registerStatic}void Register(WarScriptLanguage __script, DefinitionScope __scope)");
            sb.AppendLine($"{indent}    {{");

            if (scriptField != null)
                sb.AppendLine($"{indent}        {scriptField} = __script;");

            foreach (var f in functions)
            {
                var parameters = f.Method.GetParameters();
                var wsParamNames = parameters
                    .Where(p => p.GetCustomAttribute<WsRawArgsAttribute>() == null)
                    .Select(p => $"\"{p.Name}\"");

                sb.AppendLine();
                sb.AppendLine($"{indent}        __scope.AddFunction(new NativeFunctionDefinition(");
                sb.AppendLine($"{indent}            new FunctionDetails(\"{f.WsName}\", new List<string> {{ {string.Join(", ", wsParamNames)} }}),");
                sb.AppendLine($"{indent}            (__args) =>");
                sb.AppendLine($"{indent}            {{");

                // Marshal arguments
                int argIdx = 0;
                foreach (var p in parameters)
                {
                    if (p.GetCustomAttribute<WsRawArgsAttribute>() != null)
                    {
                        sb.AppendLine($"{indent}                var @{SafeName(p.Name)} = __args;");
                    }
                    else
                    {
                        sb.AppendLine($"{indent}                {TypeName(p.ParameterType)} @{SafeName(p.Name)} = {ArgMarshal(p.ParameterType, argIdx)};");
                        argIdx++;
                    }
                }

                // Call and marshal return
                var callArgs = string.Join(", ", parameters.Select(p => $"@{SafeName(p.Name)}"));
                var prefix = f.Method.IsStatic ? $"{type.Name}." : "this.";

                if (f.Method.ReturnType == typeof(void))
                {
                    sb.AppendLine($"{indent}                {prefix}{f.Method.Name}({callArgs});");
                    sb.AppendLine($"{indent}                return WarValue.Null;");
                }
                else
                {
                    sb.AppendLine($"{indent}                var __result = {prefix}{f.Method.Name}({callArgs});");
                    sb.AppendLine($"{indent}                return {ReturnMarshal(f.Method.ReturnType)};");
                }

                sb.AppendLine($"{indent}            }},");
                sb.AppendLine($"{indent}            \"{Esc(f.Doc)}\",");
                sb.AppendLine($"{indent}            \"{Esc(f.Returns)}\"));");
            }

            // ── Constants ──
            foreach (var c in constants)
            {
                sb.AppendLine();
                sb.AppendLine($"{indent}        // const {c.WsName}");
                var val = c.Field.GetRawConstantValue();
                var valExpr = ConstValueLiteral(c.Field.FieldType, val);
                sb.AppendLine($"{indent}        __script.GlobalMemoryScope.Set(\"{Esc(c.WsName)}\", {valExpr});");
                sb.AppendLine($"{indent}        __script.ConstantNames.Add(\"{Esc(c.WsName)}\");");
            }

            // ── Enums ──
            foreach (var e in enums)
            {
                sb.AppendLine();
                sb.AppendLine($"{indent}        // enum {e.WsName}");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            var __enumProps = new List<string>();");
                sb.AppendLine($"{indent}            var __enumDetails = new ClassDetails(\"{Esc(e.WsName)}\", __enumProps);");
                sb.AppendLine($"{indent}            var __enumScope = new DefinitionScope(__script, null);");
                sb.AppendLine($"{indent}            var __enumStmt = new WarScript.Statement.ClassStatement(__script, 0, \"{Esc(e.WsName)}\");");
                sb.AppendLine($"{indent}            var __enumDef = new ClassDefinition(__enumDetails, new List<ClassDetails>(), __enumStmt, __enumScope);");
                sb.AppendLine($"{indent}            __scope.AddClass(__enumDef);");
                sb.AppendLine();

                // Build name[] method
                sb.AppendLine($"{indent}            var __nameBody = new WarScript.Statement.FunctionStatement(__script, 0, \"{Esc(e.WsName)}#name\");");
                sb.AppendLine($"{indent}            var __nameScope = new DefinitionScope(__script, null);");
                sb.AppendLine($"{indent}            var __nameDef = new FunctionDefinition(");
                sb.AppendLine($"{indent}                new FunctionDetails(\"name\", new List<string> {{ \"value\" }}),");
                sb.AppendLine($"{indent}                __nameBody, __nameScope);");
                sb.AppendLine($"{indent}            __enumScope.AddFunction(__nameDef);");
                sb.AppendLine();

                // Emit if-chain for name[] body
                foreach (var (name, value) in e.Members)
                {
                    sb.AppendLine($"{indent}            {{");
                    sb.AppendLine($"{indent}                var __cond = new WarScript.Statement.ConditionStatement(__script, 0, \"{Esc(e.WsName)}#name\");");
                    sb.AppendLine($"{indent}                var __check = new WarScript.Expression.Operator.EqualsOperator(__script,");
                    sb.AppendLine($"{indent}                    new WarScript.Expression.VariableExpression(__script, \"value\"),");
                    sb.AppendLine($"{indent}                    new WarScript.Expression.Value.ConstantExpression(WarValue.FromNumeric({value})));");
                    sb.AppendLine($"{indent}                var __then = new WarScript.Statement.CompositeStatement(__script, 0, \"{Esc(e.WsName)}#name\");");
                    sb.AppendLine($"{indent}                __then.AddStatement(new WarScript.Statement.ReturnStatement(__script, 0, \"{Esc(e.WsName)}#name\",");
                    sb.AppendLine($"{indent}                    new WarScript.Expression.Value.ConstantExpression(WarValue.FromText(\"{Esc(name)}\"))));");
                    sb.AppendLine($"{indent}                __cond.AddCase(__check, __then);");
                    sb.AppendLine($"{indent}                __nameBody.AddStatement(__cond);");
                    sb.AppendLine($"{indent}            }}");
                }
                sb.AppendLine($"{indent}            __nameBody.AddStatement(new WarScript.Statement.ReturnStatement(__script, 0, \"{Esc(e.WsName)}#name\",");
                sb.AppendLine($"{indent}                new WarScript.Expression.Value.ConstantExpression(WarValue.FromText(\"unknown\"))));");
                sb.AppendLine();

                // Create the instance and set it as a global + constant
                sb.AppendLine($"{indent}            var __inst = new WarScript.Expression.ClassExpression(__script, \"{Esc(e.WsName)}\", new List<WarScript.Expression.IExpression>());");
                sb.AppendLine($"{indent}            __script.DefinitionContext.PushScope(__scope);");
                sb.AppendLine($"{indent}            __script.MemoryContext.PushScope(__script.GlobalMemoryScope);");
                sb.AppendLine($"{indent}            try");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                var __val = __inst.Evaluate();");

                // Set member values on the instance
                foreach (var (name, value) in e.Members)
                    sb.AppendLine($"{indent}                __val.ClassValue.SetProperty(\"{Esc(name)}\", WarValue.FromNumeric({value}));");

                // Set values array
                sb.Append($"{indent}                __val.ClassValue.SetProperty(\"values\", WarValue.FromArray(new List<WarValue> {{ ");
                sb.Append(string.Join(", ", e.Members.Select(m => $"WarValue.FromNumeric({m.Value})")));
                sb.AppendLine(" }));");

                // Set names array
                sb.Append($"{indent}                __val.ClassValue.SetProperty(\"names\", WarValue.FromArray(new List<WarValue> {{ ");
                sb.Append(string.Join(", ", e.Members.Select(m => $"WarValue.FromText(\"{Esc(m.Name)}\")")));
                sb.AppendLine(" }));");

                // Set count
                sb.AppendLine($"{indent}                __val.ClassValue.SetProperty(\"count\", WarValue.FromNumeric({e.Members.Count}));");

                sb.AppendLine($"{indent}                __script.GlobalMemoryScope.Set(\"{Esc(e.WsName)}\", __val);");
                sb.AppendLine($"{indent}                __script.ConstantNames.Add(\"{Esc(e.WsName)}\");");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}            finally");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                __script.MemoryContext.EndScope();");
                sb.AppendLine($"{indent}                __script.DefinitionContext.EndScope();");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}        }}");
            }

            sb.AppendLine($"{indent}    }}");

            // ── LibraryInfo property ──
            sb.AppendLine();
            sb.AppendLine($"{indent}    public {registerStatic}WarScriptLibraryRegistry.LibraryInfo LibraryInfo => new WarScriptLibraryRegistry.LibraryInfo");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        Name = \"{Esc(moduleAttr.Name)}\",");
            sb.AppendLine($"{indent}        Description = \"{Esc(moduleAttr.Description ?? "")}\",");
            sb.AppendLine($"{indent}        Register = {(isStatic ? "" : "this.")}Register");
            sb.AppendLine($"{indent}    }};");

            sb.AppendLine($"{indent}}}");
            if (!string.IsNullOrEmpty(ns)) sb.AppendLine("}");

            return sb.ToString();
        }

        // ────────────────────────────────────────────────────────
        //  Helpers
        // ────────────────────────────────────────────────────────

        private static string? FindScriptField(Type type)
        {
            foreach (var f in type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance))
                if (f.GetCustomAttribute<WsScriptAttribute>() != null) return f.Name;
            foreach (var p in type.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance))
                if (p.GetCustomAttribute<WsScriptAttribute>() != null) return p.Name;
            return null;
        }

        private static string ArgMarshal(Type t, int i)
        {
            if (t == typeof(double)) return $"NativeHelper.NumericArg(__args, {i})";
            if (t == typeof(int)) return $"(int)NativeHelper.NumericArg(__args, {i})";
            if (t == typeof(float)) return $"(float)NativeHelper.NumericArg(__args, {i})";
            if (t == typeof(string)) return $"NativeHelper.TextArg(__args, {i})";
            if (t == typeof(bool)) return $"(__args[{i}].IsLogical ? __args[{i}].LogicalValue : __args[{i}].IsNumeric && __args[{i}].Numeric != 0)";
            if (t.FullName == "WarScript.Expression.Value.WarValue") return $"__args[{i}]";
            if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(List<>))
                return $"NativeHelper.ArrayArg(__args, {i}).ArrayValue";
            return $"NativeHelper.NativeArg<{TypeName(t)}>(__args, {i})";
        }

        private static string ReturnMarshal(Type t)
        {
            if (t == typeof(double) || t == typeof(int) || t == typeof(float))
                return "WarValue.FromNumeric(__result)";
            if (t == typeof(string))
                return "__result != null ? WarValue.FromText(__result) : WarValue.Null";
            if (t == typeof(bool))
                return "WarValue.FromLogical(__result)";
            if (t.FullName == "WarScript.Expression.Value.WarValue")
                return "__result";
            return "WarValue.FromNativeObject(__result)";
        }

        private static string TypeName(Type t)
        {
            if (t == typeof(double)) return "double";
            if (t == typeof(int)) return "int";
            if (t == typeof(float)) return "float";
            if (t == typeof(string)) return "string";
            if (t == typeof(bool)) return "bool";
            if (t == typeof(void)) return "void";
            if (t.FullName == "WarScript.Expression.Value.WarValue") return "WarValue";
            if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(List<>))
                return $"List<{TypeName(t.GetGenericArguments()[0])}>";
            return t.Name;
        }

        private static string InferReturnsDoc(Type t)
        {
            if (t == typeof(double) || t == typeof(int) || t == typeof(float)) return "NumericValue";
            if (t == typeof(string)) return "TextValue";
            if (t == typeof(bool)) return "LogicalValue";
            if (t == typeof(void)) return "null";
            return "WarValue";
        }

        private static string ToSnakeCase(string name)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < name.Length; i++)
            {
                if (char.IsUpper(name[i]))
                {
                    if (i > 0) sb.Append('_');
                    sb.Append(char.ToLowerInvariant(name[i]));
                }
                else sb.Append(name[i]);
            }
            return sb.ToString();
        }

        private static string SafeName(string name) =>
            name == "base" || name == "class" || name == "event" || name == "object" || name == "string"
                ? name
                : name;

        private static string Esc(string s) =>
            s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n");

        private static string ConstValueLiteral(Type fieldType, object? val)
        {
            if (val == null) return "WarValue.Null";
            if (fieldType == typeof(int)) return $"WarValue.FromNumeric({(int)val})";
            if (fieldType == typeof(float)) return $"WarValue.FromNumeric({((float)val).ToString("R")}f)";
            if (fieldType == typeof(double)) return $"WarValue.FromNumeric({((double)val).ToString("R")})";
            if (fieldType == typeof(string)) return $"WarValue.FromText(\"{Esc((string)val)}\")";
            if (fieldType == typeof(bool)) return (bool)val ? "WarValue.True" : "WarValue.False";
            // Fallback for long, short, byte, etc.
            return $"WarValue.FromNumeric({Convert.ToDouble(val).ToString("R")})";
        }

        private struct FuncInfo
        {
            public MethodInfo Method;
            public string WsName;
            public string Doc;
            public string Returns;
        }

        private struct ConstInfo
        {
            public FieldInfo Field;
            public string WsName;
        }

        private struct EnumInfo
        {
            public string WsName;
            public List<(string Name, int Value)> Members;
        }
    }
}
#endif
